### ISSUE TITLE
A seaborn-like package with a Bokeh backend

### ISSUE THREAD

**Issue by apachaves** [justinbois/iqplot#15]
Please, don't let this work die, I believe it is a very good library and with good design decisions.

I was trying to find a Python package that could replicate the Seaborn API and add other things (like interactivity and tooltips) and Bokeh seemed the perfect candidate as backend for this.

Holoviews seem to have taken other design choices that make it too complex for those who just want to replicate Seaborn plots (like all the semantic matching and overlays). Since then they have also introduced Hvplot, which is very good but it looks to me too tightly entangled with Pandas, losing the flexibility with Numpy and other structures that Seaborn also has (and with a gallery of possible plots still limited compared to Seaborn).

For all that, I believe there is still room for something in the middle. I see this middle as a Seaborn-like package in terms of API complexity, using Bokeh as backend and providing extra functionalities over tooltips, interactions and other actors.

What do you think?

**Comment by justinbois** [comment]
Apologies for the looooong delay on this. In response to your comments (and thanks for them!):

1. I do not intend to let this package die. I do not intend, however, to expand it beyond the limited scope is has; high-level plotting for data sets with one quantitative variable. There are other things I could do, like violin plots and bar graphs, but they are not high on my priority list because in almost all situations I think ECDFs are better.
2. I'm a big fan on HoloViews, but one complaint I have heard from learners (my main target audience, as I am an educator), is that it is a good plotting package for _programmers_, but a little tough for users lacking sophistication or a strong OOP mindset. This is partly how iqplot was born (in addition to me being too distracted to put in ECDF functionality into HoloViews, which I found was taking a lot of time to learn the structure of plotting Elements, etc.).
3. I think Seaborn is also a lovely high level plotting package. You might want to check out it's soon-to-be-arriving interface: http://seaborn.pydata.org/nextgen/. I think adding a "something in the middle" as you're describing will make the plotting landscape even more crowded, but I don't think that's a bad thing. I suspect you'd get plenty of users for something like you're proposing. For this particular package (iqplot), I intend to keep it quite limited in scope, and I don't see many substantial changes beyond maintenance here and there going forward.

FWIW, in my workflow and with my students, I have found that iqplot is great for lots of plotting  purposes, and for the rest of things, I use base Bokeh. I have found, as I tell my students, that though it's a low-level plotting library, making high-level plots using only Bokeh is not so bad. The amount of boilerplate is not too much, and you get good control and nice, clean, intuitive construction of plots with the API.
